### ISSUE TITLE
覆写路径颜色后，暗色模式下，:focus-within 会产生位置偏移

### ISSUE THREAD

**Issue by mzwlevi** [pengx17/logseq-plugin-bullet-threading#9]
测试环境：0.8.7 原生主题，未添加 css snippets
没有覆写路径颜色正常
![Screen Shot 2022-09-25 at 11 47 25](https://user-images.githubusercontent.com/78029539/192127527-1e8a64bb-774d-4b02-8547-f06414be2441.png)
![Screen Shot 2022-09-25 at 11 47 05](https://user-images.githubusercontent.com/78029539/192127562-3a75e191-8174-4688-86b5-2461556fd310.png)

覆写路径颜色白天模式下正常
![Screen Shot 2022-09-25 at 11 47 49](https://user-images.githubusercontent.com/78029539/192127614-71a5e1b3-4279-4c8f-951e-e4aa0666eabf.png)
夜间模式下不正常
![Screen Shot 2022-09-25 at 11 48 05](https://user-images.githubusercontent.com/78029539/192127827-4e01a1b6-95e5-4c21-ad95-732f10ae926d.png)

会导致路径上所有使用 :focus-within 的 css 都会产生位置偏移

https://user-images.githubusercontent.com/78029539/192128164-415e7167-de60-4151-ae4d-88a69fb08b3b.mov

举例，使用路径上双链和标签随节点线激活高亮，位移十分明显
代码如下：
```css
.ls-block .tag {
    color: var(--ls-block-bullet-active-color);
    font-size: 16px;
    opacity: 100%;
}

.ls-block:not(:focus-within) .tag {
    color: grey;
    font-size: 16px;
    opacity: 100%;
}

.ls-block .page-ref {
    color: var(--ls-block-bullet-active-color);
    font-size: 16px;
    opacity: 100%;
}

.ls-block:not(:focus-within) .page-ref {
    color: #106ba3;
    font-size: 16px;
    opacity: 100%;
}
```
没有覆写路径颜色正常

https://user-images.githubusercontent.com/78029539/192127912-9be2f38a-28d9-4ad7-83c5-be09adfdb23d.mov
